name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - ubuntu:latest
          - debian:bookworm
          - archlinux:latest
          - fedora:42
          - fedora:41
          - fedora:40
          - fedora:39
          - fedora:38
          - fedora:37
          - fedora:36


    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies (Ubuntu)
        if: matrix.container == 'ubuntu:latest'
        run: |
          apt-get update
          apt-get install -y cmake build-essential libopenblas-dev libxsimd-dev libboost-all-dev git

      - name: Install system dependencies (Debian)
        if: startsWith(matrix.container, 'debian:')
        run: |
          apt-get update
          apt-get install -y cmake build-essential libopenblas-dev libxsimd-dev libboost-all-dev git

      - name: Install system dependencies (Arch Linux)
        if: startsWith(matrix.container, 'archlinux:')
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm cmake make gcc openblas xsimd boost git

      - name: Install system dependencies (Fedora)
        if: startsWith(matrix.container, 'fedora:')
        run: |
          dnf update -y
          dnf install -y cmake make gcc-c++ openblas-devel xsimd-devel boost-devel git

      - name: Download and install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake ..
          make
          make install

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: build
        run: cmake ..

      - name: Build project
        working-directory: build
        run: make -j$(nproc)

      - name: Run tests
        working-directory: build/test
        run: ./run_all_tests
        continue-on-error: true
    